crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crudapp.urls'))
]

crudapp/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name="index"),
    path('createEmployee', views.createEmployee, name="createEmployee"),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.delete),

]

crudapp/models.py
from django.db import models

# Create your models here.

class Employee (models.Model):
    eid = models.CharField(max_length = 20)
    ename = models.CharField(max_length = 50)
    email = models.EmailField()
    econtact = models.CharField(max_length  = 15)

crudapp/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

crudapp/views.py
from django.shortcuts import render, redirect
from .models import Employee
from .forms import EmployeeForm

# Create your views here.
def index (request):
    employes = Employee.objects.all()
    return render (request, "index.html", {'employes': employes})

def createEmployee(request):
    if request.method =="POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/')  
            except:
                pass      
    else:
        form = EmployeeForm()
        return render(request,"createEmployee.html", {'form':form})


def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,"edit.html", {'employee': employee})  


def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect('/')  
    return render(request, "edit.html", {'employee': employee}) 


def delete(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect('/')  

templates/createEmployee.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/createEmployee">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
      {{ form.eid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
      {{ form.ename }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
      {{ form.email }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
      {{ form.econtact }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{employee.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="email" id="id_eemail" required maxlength="254" value="{{ employee.email }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>  
    <title>Document</title>
</head>
<body>
   <table class="table t table-bordered table-sm">
     <thead>
      <tr>
        
        <th scope="col">Employee Id</th>
        <th scope="col">Employee Name</th>
        <th scope="col">Employee Mail</th>
        <th scope="col">Employee Contact</th>
        <th>Actions</th>  
       </tr>
      </thead>
      <tbody>
          {% for employee in employes%}
            <tr>
              
              <td>{{ employee.eid}}</td>
              <td>{{ employee.ename}}</td>
              <td>{{ employee.email}}</td>
              <td>{{ employee.econtact}}</td>
              <td>  
                    <a href="/edit/{{ employee.id }}"><span class="btn btn-warning" >Edit</span></a>  
                    <a href="/delete/{{ employee.id }}"><span class="btn btn-danger" >Delete</span></a>  
                </td>  
            </tr>
            {% endfor%}
           
          </tbody>
   </table>
   <br>  
<br>  
<center><a href="/createEmployee" class="btn btn-primary">Add New Record</a></center>  
</body>
</html>